apiVersion: v1
kind: Service
metadata:
  name: node-test
  labels:
    app: node-test
spec:
  type: ClusterIP
  selector:
    app: node-test
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
