name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ secrets.AWS_REGION }}
    - name: Build the Docker image
      run: |
       aws ecr get-login-password --region ap-south-1 | docker login --username AWS --password-stdin 642535305379.dkr.ecr.ap-south-1.amazonaws.com
       docker build -t demo-repo .
       docker tag demo-repo:latest 642535305379.dkr.ecr.ap-south-1.amazonaws.com/demo-repo:latest
       docker push 642535305379.dkr.ecr.ap-south-1.amazonaws.com/demo-repo:latest
       
